export const UG_COURSES = [
  'BA - General',
  'BA - English',
  'BA - Economics',
  'BA - History',
  'BA - Political Science',
  'BA - Public Administration',
  'BA - Sociology',
  'BA - Mathematics',
  'BA - JMC (Journalism & Mass Communication)',
  'BA - Media Studies',
  'BA (Hons) - Literary & Cultural Studies',
  'BBA - General',
  'BBA - Finance Management',
  'BBA - Marketing Management',
  'BBA - Human Resource Management',
  'BBA - Digital Marketing',
  'BBA - International Business',
  'BBA - IT & Systems Management',
  'BBA - Retail Management',
  'BBA - BFSI (Banking & Insurance)',
  'BBA - Shipping & Logistics',
  'BBA - E-Commerce Management',
  'BBA - Entrepreneurship',
  'BBA - Business Analytics',
  'BBA - Operations Management',
  'BBA - Sports Management',
  'BBA (Hons)',
  'BBA - ACCA',
  'BBA - KPMG',
  'BBA - Lenskart',
  'BCA - General',
  'BCA - AI & Data Science',
  'BCA - Data Analytics',
  'BCA - Cloud Computing & Cyber Security',
  'BCA - Fintech',
  'BCA - Game Development',
  'BCA - Software Engineering (HCLTech)',
  'BCA - New Age Technology',
  'BCA (Hons)',
  'B.Com - General',
  'B.Com (Hons)',
  'B.Com - ACCA',
  'B.Com - International',
];

export const PG_COURSES = [
  'MBA - General',
  'MBA - Finance Management',
  'MBA - Marketing Management',
  'MBA - Human Resource Management',
  'MBA - IT Management',
  'MBA - Operations Management',
  'MBA - Business Analytics',
  'MBA - Digital Marketing',
  'MBA - International Business',
  'MBA - Healthcare & Hospital Administration',
  'MBA - Logistics & Supply Chain Management',
  'MBA - Project Management',
  'MBA - Fintech',
  'MBA - Agribusiness Management',
  'MBA - Retail Management',
  'MBA - AI & Machine Learning',
  'MBA - Blockchain Management',
  'MBA - Data Science & Gen AI',
  'MBA - Banking & Insurance',
  'MBA - E-Commerce Management',
  'MBA - ESG',
  'MBA - Media Management',
  'MBA - Sales & Marketing',
  'MBA - Oil & Gas Management',
  'MBA - Power Management',
  'MBA - Infrastructure Management',
  'MBA - Digital Business',
  'MBA - Pharmaceutical Management',
  'MBA - Tourism & Event Management',
  'MBA - Public Policy',
  'MBA - Family Managed Business',
  'MBA - Entrepreneurship & Innovation',
  'MBA - International Marketing & Brand Management',
  'MBA - Supply Chain Management',
  'MBA - Dual Specialization',
  'MBA - ACCA',
  'MBA - Lenskart',
  'MBA Premium',
  'MBA Plus',
  'MCA - General',
  'MCA - Data Science',
  'MCA - AI & Machine Learning',
  'MCA - Cyber Security',
  'MCA - Game Development',
  'MCA - Generative AI',
  'MCA - Software Engineering (HCLTech)',
  'MCA - AR/VR (TCSiON)',
  'MCA - Fintech',
  'MA - English',
  'MA - JMC (Journalism & Mass Communication)',
  'MA - Economics',
  'MA - Political Science',
  'MA - Sociology',
  'MA - History',
  'MA - English Language Teaching',
  'MA - Applied Psychology',
  'MA - English (Creative Writing)',
  'M.Com - General',
  'M.Com - Financial Management',
  'M.Com - International',
  'M.Sc - Data Science',
  'M.Sc - Mathematics',
  'M.Sc - Applied Psychology',
  'M.Sc - AI & Machine Learning',
  'M.Sc - Chemistry (Organic)',
  'MSW - General',
  'M.Tech - AI & Data Science',
  'M.Tech - Computer Science & Engineering',
  'Master of Performing Arts',
];

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat',
  'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh',
  'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
  'Uttarakhand', 'West Bengal', 'Delhi', 'Jammu & Kashmir', 'Ladakh',
  'Chandigarh', 'Puducherry', 'Andaman & Nicobar Islands',
];
